title: PALINCHA HEMANTH
logo: /assets/img/logo.png
description: Data Scientist/Ml Engineer Proven Experience with  able to work with large volume of structured and unstructured data , building complex models using python, sql, machine learning, deep learning, Nlp and able to build powerful dashboard using powerbi and good knowledge in aws services and mlops(automl).
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
